//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Student", Namespace="http://localhost/myWebService1")]
    [System.SerializableAttribute()]
    public partial class Student : WebApplication1.ServiceReference1.Person {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeGField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeSField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CodeG {
            get {
                return this.CodeGField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeGField, value) != true)) {
                    this.CodeGField = value;
                    this.RaisePropertyChanged("CodeG");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CodeS {
            get {
                return this.CodeSField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeSField, value) != true)) {
                    this.CodeSField = value;
                    this.RaisePropertyChanged("CodeS");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="http://localhost/myWebService1")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebApplication1.ServiceReference1.Student))]
    public partial class Person : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AgeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Age {
            get {
                return this.AgeField;
            }
            set {
                if ((object.ReferenceEquals(this.AgeField, value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost/myWebService1", ConfigurationName="ServiceReference1.Service1Soap")]
    public interface Service1Soap {
        
        // CODEGEN: Generating message contract since element name Get_StudentsResult from namespace http://localhost/myWebService1 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/myWebService1/Get_Students", ReplyAction="*")]
        WebApplication1.ServiceReference1.Get_StudentsResponse Get_Students(WebApplication1.ServiceReference1.Get_StudentsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Get_StudentsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Get_Students", Namespace="http://localhost/myWebService1", Order=0)]
        public WebApplication1.ServiceReference1.Get_StudentsRequestBody Body;
        
        public Get_StudentsRequest() {
        }
        
        public Get_StudentsRequest(WebApplication1.ServiceReference1.Get_StudentsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class Get_StudentsRequestBody {
        
        public Get_StudentsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Get_StudentsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Get_StudentsResponse", Namespace="http://localhost/myWebService1", Order=0)]
        public WebApplication1.ServiceReference1.Get_StudentsResponseBody Body;
        
        public Get_StudentsResponse() {
        }
        
        public Get_StudentsResponse(WebApplication1.ServiceReference1.Get_StudentsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/myWebService1")]
    public partial class Get_StudentsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebApplication1.ServiceReference1.Student[] Get_StudentsResult;
        
        public Get_StudentsResponseBody() {
        }
        
        public Get_StudentsResponseBody(WebApplication1.ServiceReference1.Student[] Get_StudentsResult) {
            this.Get_StudentsResult = Get_StudentsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : WebApplication1.ServiceReference1.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<WebApplication1.ServiceReference1.Service1Soap>, WebApplication1.ServiceReference1.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.ServiceReference1.Get_StudentsResponse WebApplication1.ServiceReference1.Service1Soap.Get_Students(WebApplication1.ServiceReference1.Get_StudentsRequest request) {
            return base.Channel.Get_Students(request);
        }
        
        public WebApplication1.ServiceReference1.Student[] Get_Students() {
            WebApplication1.ServiceReference1.Get_StudentsRequest inValue = new WebApplication1.ServiceReference1.Get_StudentsRequest();
            inValue.Body = new WebApplication1.ServiceReference1.Get_StudentsRequestBody();
            WebApplication1.ServiceReference1.Get_StudentsResponse retVal = ((WebApplication1.ServiceReference1.Service1Soap)(this)).Get_Students(inValue);
            return retVal.Body.Get_StudentsResult;
        }
    }
}
